/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasir;

import auth.logOut;
import auth.login;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import models.sessionID;

/**
 *
 * @author DELL
 */
public class kasir extends javax.swing.JFrame {

    /**
     * Creates new form kasir
     * @throws java.sql.SQLException
     */
    public kasir() throws SQLException {
        initComponents();
         
        setTitle("DAPUR RESTORAN JAVA");
        setPreferredSize(new Dimension(1024, 768));
        setResizable(false);
        setLocationRelativeTo(null);
        
        String nama = sessionID.getUserName();
        welcomeMsg.setText("Selamat datang, " + nama);
        
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logOut = new javax.swing.JLabel();
        newLink = new javax.swing.JLabel();
        payLink = new javax.swing.JLabel();
        listLink = new javax.swing.JLabel();
        welcomeMsg = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/logout-32.png"))); // NOI18N
        logOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutMouseClicked(evt);
            }
        });
        getContentPane().add(logOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 390, -1, -1));

        newLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/new32.png"))); // NOI18N
        newLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newLinkMouseClicked(evt);
            }
        });
        getContentPane().add(newLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, -1, -1));

        payLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/pay2.png"))); // NOI18N
        payLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        payLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payLinkMouseClicked(evt);
            }
        });
        getContentPane().add(payLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 390, -1, -1));

        listLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icon/list.png"))); // NOI18N
        listLink.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listLinkMouseClicked(evt);
            }
        });
        getContentPane().add(listLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 390, -1, -1));

        welcomeMsg.setFont(new java.awt.Font("Kristen ITC", 1, 18)); // NOI18N
        welcomeMsg.setForeground(new java.awt.Color(255, 255, 255));
        welcomeMsg.setText("Selamat datang, {{dapurName}}");
        getContentPane().add(welcomeMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 310, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background/kasir/kasir home.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newLinkMouseClicked
        try {
            new createOrder().setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(kasir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_newLinkMouseClicked

    private void payLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payLinkMouseClicked
        try {
            new orderLists().setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(kasir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_payLinkMouseClicked

    private void listLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listLinkMouseClicked
        try {
            new orderLists().setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(kasir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_listLinkMouseClicked

    private void logOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutMouseClicked
        new logOut().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logOutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new kasir().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(kasir.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel listLink;
    private javax.swing.JLabel logOut;
    private javax.swing.JLabel newLink;
    private javax.swing.JLabel payLink;
    private javax.swing.JLabel welcomeMsg;
    // End of variables declaration//GEN-END:variables
}
