/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package auth;

import admin.admin;
import dapur.dapur;
import java.awt.Dimension;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import kasir.kasir;
import models.mysql;
import models.sessionID;
import  models.helperClass;

/**
 *
 * @author DELL
 */
public class login extends javax.swing.JFrame {
    private mysql db;
    private Statement stm;
    private ResultSet res;
    private HashMap<Integer, String> userGrant;

    /**
     * Creates new form masuk
     */
    public login() throws SQLException {
        initComponents();
        
        setTitle("LOGIN RESTORAN JAVA");
        setPreferredSize(new Dimension(500, 800));
        setResizable(false);
        setLocationRelativeTo(null);
        
        userField.setOpaque(false);
        
        this.db = new mysql();
        this.stm = mysql.getConnection().createStatement();
        this.userGrant = new HashMap<Integer, String>();
        
        userAlert.setVisible(false);
        passAlert.setVisible(false);
        loginTxt.setVisible(false);
        
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        passField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JLabel();
        userAlert = new javax.swing.JLabel();
        passAlert = new javax.swing.JLabel();
        loginTxt = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userField.setFont(new java.awt.Font("Kristen ITC", 2, 14)); // NOI18N
        userField.setForeground(new java.awt.Color(241, 66, 4));
        getContentPane().add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 150, 40));

        passField.setFont(new java.awt.Font("Kristen ITC", 2, 14)); // NOI18N
        passField.setForeground(new java.awt.Color(241, 66, 4));
        getContentPane().add(passField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 150, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background/login/username label.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background/login/input background.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, 80));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background/login/password label.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background/login/input background.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, 80));

        loginBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background/login/btn.png"))); // NOI18N
        loginBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBtnMouseClicked(evt);
            }
        });
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, -1, -1));

        userAlert.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        userAlert.setForeground(new java.awt.Color(255, 255, 255));
        userAlert.setText("{{userAlert}}");
        getContentPane().add(userAlert, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        passAlert.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        passAlert.setForeground(new java.awt.Color(255, 255, 255));
        passAlert.setText("{{passAlert}}");
        getContentPane().add(passAlert, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, -1, -1));

        loginTxt.setFont(new java.awt.Font("Franklin Gothic Book", 1, 14)); // NOI18N
        loginTxt.setForeground(new java.awt.Color(255, 255, 255));
        loginTxt.setText("{{loginTxt}}");
        getContentPane().add(loginTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/background/login/background.jpg"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBtnMouseClicked
        String user = userField.getText();
        String pass = passField.getText();

        if(user.equals("")) {
            userAlert.setText("Masukkan username!");
            userAlert.setVisible(true);
        }
        else {
            userAlert.setVisible(false);
        }

        if(pass.equals("")) {
            passAlert.setText("Masukkan password!");
            passAlert.setVisible(true);
        }
        else {
            passAlert.setVisible(false);
        }

        if( ! user.equals("") && ! pass.equals("")) {
            try {
                /*
                * Perbaikan 1: untuk mengatasi SQL Injection pada from Login
                * kita gunakan preparedStatement()
                *
                * @bg Meyzan
                */
                String cekUser = "SELECT * FROM `users` WHERE `username` = ?";
                PreparedStatement pes = mysql.connect.prepareStatement(cekUser);
                pes.setString(1, user);
                this.res = pes.executeQuery();

                if(this.res.next()) {
                    String login = "SELECT * FROM `users` WHERE `username` = ? AND `password` = ?";
                    PreparedStatement ps = mysql.connect.prepareStatement(login);
                    ps.setString(1, user);
                    ps.setString(2, helperClass.getMD5(pass));
                    this.res = ps.executeQuery();

                    if(this.res.next()) {
                        int userID = this.res.getInt("userID");

                        String userProfile = "SELECT u.userID, u.userGrant, p.fullName FROM users u JOIN userProfile p ON u.userID = p.userID WHERE u.userID = '"+ userID +"'";
                        this.res = this.stm.executeQuery(userProfile);

                        if(this.res.next()) {
                            int userGrant = this.res.getInt("userGrant");
                            String userName = this.res.getString("fullName");

                            sessionID.setUserGrant(userGrant);
                            sessionID.setUserID(userID);
                            sessionID.setUserName(userName);
                            
                            userField.setText("");
                            passField.setText("");
                            
                            this.dispose();
                            this.setVisible(false);
                            
                            if(userGrant == 1)
                                new admin().setVisible(true);
                            else if(userGrant == 2)
                                new kasir().setVisible(true);
                            else if(userGrant == 3)
                                new dapur().setVisible(true);
                        }
                    }
                    else {
                        loginTxt.setText("Password salah!");
                        loginTxt.setVisible(true);
                        
                        passField.setText("");
                        passField.requestFocus();
                    }
                }
                else {
                    userAlert.setText("User "+ user +" tidak terdaftar!");
                    userAlert.setVisible(true);
                    
                    userField.setText("");
                    userField.requestFocus();
                }
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_loginBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new login().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel loginBtn;
    private javax.swing.JLabel loginTxt;
    private javax.swing.JLabel passAlert;
    private javax.swing.JPasswordField passField;
    private javax.swing.JLabel userAlert;
    private javax.swing.JTextField userField;
    // End of variables declaration//GEN-END:variables
}
